# Generated by Django 2.2.11 on 2020-03-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200328_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='media',
            field=models.CharField(blank=True, choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=20),
        ),
    ]
