# Generated by Django 2.2.11 on 2020-03-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_userprofile_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
